cart/urls.py
from django.urls import path

from . import views
app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name = 'cart_detail'),
    path('add/<product_id>/', views.cart_add, name = 'cart_add'),
    path('remove/<product_id>', views.cart_remove, name = 'cart_remove'),
    path('clear',views.cart_clear, name = 'cart_clear'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls', namespace='mainpage.mainpage')),
    path('products/', include('products.urls', namespace='products.products')),
    path('contacts/', include('contacts.urls', namespace='contacts.contacts')),
    path('cart/', include('cart.urls', namespace='cart.cart')),\
    path('orders/', include('orders.urls', namespace='orders.orders')),
    path('users/', include('users.urls', namespace='users.users')),
    path('pages/', include('pages.urls', namespace='pages.pages')),
    #USERS
    path('accounts/login', LoginView.as_view(template_name='users/registration/login.html'), name='login'),
    path('accounts/logout', LogoutView.as_view(template_name='users/registration/logout.html'), name='logout'),
    #CAPTCHA
    path('captcha/', include('captcha.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

orders/urls.py
from email.mime import base
from django.urls import path

from orders.models import Order
from .views import OrderPayment, order_create, OrderDetailView, OrderAPIView, OrderPaymentAPIView
from rest_framework.routers import DefaultRouter
app_name = 'orders'
router = DefaultRouter()
router.register('payment', OrderAPIView, basename='payment')

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('<int:pk>/qr/', OrderPayment.as_view(), name='order_qr'),
    path('<int:pk>/detail/', OrderDetailView.as_view(), name='order_detail'),
    # Payment
    path('<int:pk>/paid/<int:paid>', OrderPaymentAPIView.as_view(), name='paid')
]
urlpatterns += router.urls

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from statistics import quantiles
from django import forms

class CartAddProductForm(forms.Form):
    quantity = forms.CharField(label='Количество')
    update = forms.BooleanField(required=False, initial=False, widget = forms.HiddenInput)
    page_id = forms.IntegerField(),

    class Meta:
        fields = ('quantity', 'update')
        widgets = {
            'quantity': forms.TextInput(
                attrs={'class': 'product_quantity js_numder',
                'value' : 1}),

      

        'update' : forms.HiddenInput(),
        'page_id' : forms.HiddenInput(),
        }

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
# Create your views here.
from  products.models import SingleProduct
from .services.cart import Cart

from .forms import CartAddProductForm
from icecream import ic


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(SingleProduct, pk=product_id)
    
    form = CartAddProductForm(request.POST)
    # s
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])

    return redirect('products:show_single_product_page', request.POST.get('page_id'))

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(SingleProduct, pk=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    template_name = 'cart/cart_detail.html'
    context = {'cart' : Cart(request)}

    return render(request=request, template_name=template_name, context=context)

def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')

templates/cart/cart_detail.html
{% extends 'layout/base.html' %}

{% block title %}
    {{ product.name }}
{% endblock title %}
    
{% block content %}
{% load static %}
<section class="container">
    <h1>Корзина</h1>
    {% if user.is_authenticated %}
    <table class="cart table table-fluid">
        <thead>
        <tr>
            <th>Изображение</th>
            <th>Товар</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Стоимость за единицу</th>
            <th>Цена</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.images.all.0.image %}
                                    {{ product.images.all.0.image.url }}
                                {% else %}
                                    {% static "images/logo/logo_x_72.png" %}
                                {% endif %}" height="150">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url "cart:cart_remove" product.id%}">Удалить</a></td>
                    <td class="num">{{ item.price }}</td>
                    <td class="num">{{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Итого</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
        <tfoot>
            <tr>
                <td><a href="{% url 'cart:cart_clear' %} ">Clear whole cart</a></td>
                <td><a class="btn btn-primary" href="{% url 'orders:order_create'%}">Сделать заказ</a></td>
            </tr>
        </tfoot>
    </table>
    <p class="text-right">
        <!-- <div class="btn-button-group mg-top-30 mg-bottom-15 bt-contact"> -->
            
            {% comment %}
                <a class="zoa-btn btn-login hover-white contact" href="{% url 'orders:order_create' %}" class="button">Купить</a>
            {% endcomment %}
                
        <!-- </div> -->


    </p>
    {% else %}
        <p>Вы не авторизованы</p>
        <a href="{% url 'login' %}" class="button">Войти</a>

    {% endif %}
</section>
{% endblock content %}