cart/urls.py
from django.urls import path

from . import views
app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name = 'cart_detail'),
    path('add/<product_id>/', views.cart_add, name = 'cart_add'),
    path('remove/<product_id>', views.cart_remove, name = 'cart_remove'),
    path('clear',views.cart_clear, name = 'cart_clear'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls', namespace='mainpage.mainpage')),
    path('products/', include('products.urls', namespace='products.products')),
    path('contacts/', include('contacts.urls', namespace='contacts.contacts')),
    path('cart/', include('cart.urls', namespace='cart.cart')),\
    path('orders/', include('orders.urls', namespace='orders.orders')),
    path('users/', include('users.urls', namespace='users.users')),
    path('pages/', include('pages.urls', namespace='pages.pages')),
    #USERS
    path('accounts/login', LoginView.as_view(template_name='users/registration/login.html'), name='login'),
    path('accounts/logout', LogoutView.as_view(template_name='users/registration/logout.html'), name='logout'),
    #CAPTCHA
    path('captcha/', include('captcha.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

orders/urls.py
from email.mime import base
from django.urls import path

from orders.models import Order
from .views import OrderPayment, order_create, OrderDetailView, OrderAPIView, OrderPaymentAPIView
from rest_framework.routers import DefaultRouter
app_name = 'orders'
router = DefaultRouter()
router.register('payment', OrderAPIView, basename='payment')

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('<int:pk>/qr/', OrderPayment.as_view(), name='order_qr'),
    path('<int:pk>/detail/', OrderDetailView.as_view(), name='order_detail'),
    # Payment
    path('<int:pk>/paid/<int:paid>', OrderPaymentAPIView.as_view(), name='paid')
]
urlpatterns += router.urls

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from products.models import SingleProduct
# Create your models here.
from .managers import OrderItemManager


class Order(models.Model):
    user = models.ForeignKey(
        verbose_name=_('Пользователь'),
        to=User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='order_related_user'
    )
    created_at = models.DateTimeField(
        verbose_name=_('Дата создания'), auto_now_add=True)
    first_name = models.CharField(verbose_name=_('Имя'), max_length=50)
    last_name = models.CharField(verbose_name=_('Фамилия'), max_length=50)
    phone = models.CharField(verbose_name=_('Телефон'), max_length=14)
    email = models.EmailField(verbose_name=_('email'))
    address = models.CharField(verbose_name=_('Адрес'), max_length=250)
    postal_code = models.CharField(verbose_name=_('Индекс'), max_length=20)
    city = models.CharField(verbose_name=_('Город'), max_length=100)

    updated_at = models.DateTimeField(
        verbose_name=_('Дата обновления'), auto_now=True)
    paid = models.BooleanField(verbose_name=_('Оплачен'), default=False)

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Order {self.pk}'


class OrderItem(models.Model):
    order = models.ForeignKey(
        verbose_name=_('Заказ'),
        to=Order,
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
            verbose_name=_('Товар'),
            to= SingleProduct,
            on_delete=models.CASCADE,
        )
    price = models.DecimalField(verbose_name=_('Цена'), max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(verbose_name=_('Количество'))
    sale_percent = models.PositiveIntegerField(verbose_name=_('Процент скидки'), default=0)

    sale_price = models.DecimalField(verbose_name=_('Цена скидки'),
    max_digits=10, 
    decimal_places=2,
    blank=True,
    null =True)

    objects = models.Manager()
    items = OrderItemManager()

    class Meta:
        verbose_name = _('Товар в заказе')
        verbose_name_plural = _('Товары в заказе')

    def __str__(self):
        return f'{self.order.pk}'

    def total_price(self):
        total = self.price * self.quantity
        return total


    

orders/forms.py
from django import forms
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField
from .models import Order

class OrderCreateForm(forms.ModelForm):
    captcha = CaptchaField(label="Введите картинку")
    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 
            'email', 'phone', 'address',
            'postal_code', 'city'
        )
        

orders/views.py
from icecream import ic
from django.shortcuts import render, get_object_or_404

# Create your views here.
from  django.views.generic import (
    DetailView,
)
from .forms import (
    OrderCreateForm,
)
from rest_framework import generics, viewsets

from .serializers import OrderSerializer, OrderPaymentSerializer

from cart.services.cart import Cart
from django.db import transaction
from .models import Order, OrderItem

def make_qrr(pk, cart=None):
        import qrcode

        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.ERROR_CORRECT_L,
            box_size=10,
            border=4
        )
        qr.add_data(
            {
                'order_url' : f"https://uzumbank.uz/ru/orders/{pk}",
                'order_id' : pk,
                'cart' : cart
            }
            )
        qr.make()
        img = qr.make_image(fill_color ='black', back_color ='white')
        order_id = pk

        img.save(f'media/qrs/order_{order_id}_qr.png')
        return order_id




def commit_handler():
    return 'Transaction done'
# @transaction.atomic
def order_create(request):
    template_name = "pages/orders/order_created.html"
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            form.clean()

        if form.cleaned_data:
            save_point = transaction.savepoint()
            order.user = request.user
            order.email = request.user.email
            order.phone = form.cleaned_data.get('phone')
            order.address = form.cleaned_data.get('address')
            order.postal_code = form.cleaned_data.get('postal_code')
            order.city = form.cleaned_data.get('city')

            try:
                
                order.save()
                transaction.savepoint_commit(save_point)
                

            except:
                transaction.rollback(save_point)
            
            transaction.commit()
            transaction.on_commit(commit_handler)

        for item in cart:
            order_item = OrderItem.objects.create(
                product = item['product'],
                price = item['end_price'],
                quantity = item['quantity'],
                order = order,
            )
        #очистка корзины
        qr  = make_qrr(order.pk, cart)
        cart.clear()
        
        return render(
            request=request, template_name=template_name,context={'order':order, 'qr': qr}
        )
    else:
        
        if request.user.is_authenticated:
            ic('get request')
            form = OrderCreateForm(
                initial={
                    'user':request.user,
                    'first_name':request.user.first_name,
                    'last_name':request.user.last_name,
                    'customer_id' : request.user.pk
                }
            )
        else:
            form = OrderCreateForm()

    return render(
        request, 'pages/orders/order_create.html', {'cart' : cart, 'form' : form}
    )



class OrderPayment(DetailView):
    model = Order
    template_name = 'pages/orders/order_payment.html'
    context_object_name = 'order'

    def get_context_data(self, **kwargs):
        context = super(OrderPayment, self).get_context_data(**kwargs)
        context['qr'] = make_qrr(pk = kwargs['object'].pk)

        return context
    

 
class OrderDetailView(DetailView):
    model = Order
    template_name = 'pages/orders/order_detail.html'
    context_object_name = 'order'

    def get_context_data(self, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)

        context['order_items'] = OrderItem.items.order_items(kwargs['object'].pk)
        context['order'] = Order.objects.select_related('user').get(
            pk = kwargs['object'].pk
        )
        context['order_price'] = sum(
            [item.price * item.quantity for item in context['order_items']]
        )
        return context



#Orders Api

class OrderAPIView(viewsets.ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

class OrderPaymentAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Order.objects.all()
    serializer_class = OrderPaymentSerializer
    
    def get(self, request, *args, **kwargs):
        payment = get_object_or_404(Order, pk=kwargs['pk'])
        if kwargs['paid']:
            payment.paid = True
        else:
            payment.paid = False
        payment.save()

        return self.retrieve(request, *args, **kwargs)

        

templates/pages/orders/order_change_detail.html
{% extends 'layout/base.html' %}


{% block title %}
    {{ category.name }}
{% endblock title %}
    
{% block content %}
{% load static %}
<section>

    <form action="." method="post" class="order-form">
        <p><input type="submit" value="Place order"></p>
        {{ order_formset.as_p }}

        {% csrf_token %}
    </form>
    
</section>

{% endblock content %}

templates/pages/orders/order_create.html
z`{% extends 'layout/base.html' %}


{% block title %}
{{ category.name }}
{% endblock title %}

{% block content %}

<h1 class="">Заказы</h1>
<section class="container">
    <div class="row-fluid">
        <div class="col-md-6 col-xl-6">
            <div class="order-info">
                <h3>Ваш заказ</h3>
                <table>
                    <tbody>
                        {% for item in cart %}
                        <tr>
                            <td>{{ item.quantity }} x {{ item.product.name }}</td>
                            <td><span> {{ item.total_price }}</span></td>
                            </li>
                            {% endfor %}
                        <tr>
                            <td colspan="2">Итого: {{ cart.get_total_price }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>


        <div class="col-md-6 col-xl-6">
            
            <table>
                <form action="." method="post" class="order-form">
                    {% csrf_token %}
                    {% load django_bootstrap5 %}
                    {% bootstrap_messages %} 
                    {% bootstrap_form form layout="horizontal" size='sm' %}
                    {# {% bootstrap_form form layout="inline" size='sm' %} #}
                    {% bootstrap_button buttton_type='submit' content='Ok' size='md' %}
                    {% bootstrap_button buttton_type='reset' content='Cancel' size='md'  %}

                    {# {{ form.as_table }} #}
                    <!-- <tr>
                        <td colspan="2">
                            <div class="btn-button-group mg-top-30 mg-bottom-15 bt-contact">
                                <button class="zoa-btn btn-login hover-white contact" type="submit" value="Разместить заказ">Разместить заказ</button>
                            </div>
        
                        </td> -->
                    </tr>
                </form> 
            </table>
        </div>
    </div>
</section>
{% endblock content %}

templates/pages/orders/order_created.html
{% extends 'layout/base.html' %}


{% block title %}
    {{ category.name }}
{% endblock title %}
    
{% block content %}
<h1>Спасибо</h1>
<p class="dark">Ваш заказ был успешно оформлен. Мы свяжемся с вами в ближайшее время.</p>
<p class="dark">Номер Вашего заказа </p>
    <strong  class="dark">{{ order.id }}</strong>.  
    <img src="/media/qrs/order_{{order.pk}}_qr.png" alt="">
<a class="btn btn-primary" href="{% url 'orders:order_detail' qr %}">Перейти к деталям заказа</a>

{% endblock %}

templates/pages/orders/order_detail.html
{% extends 'layout/base.html' %}


{% block title %}
{{ order.pk }}
{% endblock title %}

{% block content %}
<section class="wrappage">
    
    {% if user.is_authenticated %}
    <div class="container">
        <h1>Заказ № {{ order.pk }}
            {% if order.paid %}
            <span class="badge badge-success">Оплачен</span>
            {% else %}
            <span class="badge badge-danger">Не оплачен</span>
            {% endif %}
        </h1>
        <div class="row-fluid justify-content-center">
            <table class="table table-responsive">
                <thead>
                    <tr>
                        <th>Изображение</th>
                        <th>Наименование</th>
                        <th>Цена</th>
                        <th>Количество</th>
                        <th>Сумма</th>
                </thead>

                <tbody>

                    {% for item_order in order_items.all %}
                    <tr>
                        <td>
                            {% for item_image in item_order.product.images.all %}
                            {% if forloop.first %}
                            <img src="{{ item_image.image.url }}" class="img-reponsive" width="150">
                            {% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            {{ item_order.product.name }}
                        </td>
                        <td>
                            {{ item_order.product.price }}
                        </td>
                        <td>
                            {{ item_order.quantity }}
                        </td>
                        <td>
                            {{ item_order.total_price }}
                        </td>
                    </tr>

                    {% endfor %}
                    <tr>
                        <td colspan="4">
                        </td>
                        <td>
                            <h4>Итого: {{ order_price }}</h4>

                            {% if not order.paid %}
                                <div class="btn-button-group mg-top-30 mg-bottom-15 bt-contact"></div>
                                <a class="zoa-btn btn-login hover-white contact"
                                    href="{% url 'orders:order_qr' order.pk %}">Оплата</a>
                                </div>
                            {% endif %}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
    <h2> Вам необходимо войти </h2>
    <div class="btn-button-group mg-top-30 mg-bottom-15 bt-contact"></div>
    <a class="zoa-btn btn-login hover-white contact" href="{% url 'login' %}">Войти</a>
    </div>
    {% endif %}

</section>

{% endblock content %}

templates/pages/orders/order_payment.html
{% extends 'layout/base.html' %}


{% block title %}
    Оплата
{% endblock title %}
    
{% block content %}
<h1>QR код для оплаты</h1>
        
    {{ order }}
    {{ order_items }}
    
    
    <img src="/media/qrs/order_{{order.pk}}_qr.png" alt="">
{% endblock content %}