cart/urls.py
from django.urls import path

from . import views
app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name = 'cart_detail'),
    path('add/<product_id>/', views.cart_add, name = 'cart_add'),
    path('remove/<product_id>', views.cart_remove, name = 'cart_remove'),
    path('clear',views.cart_clear, name = 'cart_clear'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls', namespace='mainpage.mainpage')),
    path('products/', include('products.urls', namespace='products.products')),
    path('contacts/', include('contacts.urls', namespace='contacts.contacts')),
    path('cart/', include('cart.urls', namespace='cart.cart')),\
    path('orders/', include('orders.urls', namespace='orders.orders')),
    path('users/', include('users.urls', namespace='users.users')),
    path('pages/', include('pages.urls', namespace='pages.pages')),
    #USERS
    path('accounts/login', LoginView.as_view(template_name='users/registration/login.html'), name='login'),
    path('accounts/logout', LogoutView.as_view(template_name='users/registration/logout.html'), name='logout'),
    #CAPTCHA
    path('captcha/', include('captcha.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import(

    AllProductsView, 
    add_file,
    get_file,
    index_files,
    delete_file,
)

app_name = 'pages'

urlpatterns = [
    path('all_products', AllProductsView.as_view(), name='all_products'),
    path('add_file',add_file,name = 'add_file'),
    path('files/get/<path:filename>', get_file, name = 'get_file'),
    path('files/',index_files, name='index_files'),
    path('files/delete/<path:filename>', delete_file, name = 'delete_file'),

 ]

templates/pages/files/add_file.html
{% extends 'layout/base.html' %}


{% block content %}
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save file">
    </form>
{% endblock content %}
    

templates/pages/files/indexx.html
{% extends 'layout/base.html' %}


{% block content %}
    <section>
        <div>
            
            {% if no_files %}
                <h2>{{ no_files }}</h2>
                <a href="{% url 'pages:add_file' %}">Добавить файл</a>
            {% else %}
            
            {% for file  in files %}
                Файл:
                <a href="{% url 'pages:get_file' filename=file %}">{{ file }}</a>
                <a href="{% url 'pages:delete_file' filename=file %}" class="btn btn-primary">Delete File</a>
                <br>
            {% endfor %}
                
            {% endif %}
                
        </div>

    </section>
{% endblock content %}
    