cart/urls.py
from django.urls import path

from . import views
app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name = 'cart_detail'),
    path('add/<product_id>/', views.cart_add, name = 'cart_add'),
    path('remove/<product_id>', views.cart_remove, name = 'cart_remove'),
    path('clear',views.cart_clear, name = 'cart_clear'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls', namespace='mainpage.mainpage')),
    path('products/', include('products.urls', namespace='products.products')),
    path('contacts/', include('contacts.urls', namespace='contacts.contacts')),
    path('cart/', include('cart.urls', namespace='cart.cart')),\
    path('orders/', include('orders.urls', namespace='orders.orders')),
    path('users/', include('users.urls', namespace='users.users')),
    path('pages/', include('pages.urls', namespace='pages.pages')),
    #USERS
    path('accounts/login', LoginView.as_view(template_name='users/registration/login.html'), name='login'),
    path('accounts/logout', LogoutView.as_view(template_name='users/registration/logout.html'), name='logout'),
    #CAPTCHA
    path('captcha/', include('captcha.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

contacts/urls.py
from django.urls import path
from .views import(
 ContactPageDetailView,
 SuccessContactMeassageView,
 )
app_name = 'contacts'
urlpatterns = [
    path('', ContactPageDetailView.as_view() , name='contact_page_form_view'),
    path('successful_message', SuccessContactMeassageView.as_view(), name='success_contact_message')
    
]

mainpage/urls.py
from django.urls import path
from .views import MainPageTemplateView
app_name = 'mainpage'
urlpatterns = [
     path('', MainPageTemplateView.as_view(), name='show_mainpage')
]

pages/urls.py
from django.urls import path
from .views import(

    AllProductsView, 
    add_file,
    get_file,
    index_files,
    delete_file,
)

app_name = 'pages'

urlpatterns = [
    path('all_products', AllProductsView.as_view(), name='all_products'),
    path('add_file',add_file,name = 'add_file'),
    path('files/get/<path:filename>', get_file, name = 'get_file'),
    path('files/',index_files, name='index_files'),
    path('files/delete/<path:filename>', delete_file, name = 'delete_file'),

 ]

templates/layout/base.html
{% load static %}

{% comment %}
{% load django_bootstrap5 %}
{% endcomment %}
    

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online Store</title>
        <!-- Google Fonts -->
        <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>
        
        <!-- Bootstrap -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        
        <!-- Font Awesome -->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        
        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

        <!-- CONTACtFORMS CSS -->
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        
        <link rel="stylesheet" href="{% static 'forms/css/style.css'" %}>
        
        {% comment %}
        {% bootstrap_css %}
        {% endcomment %}
            
        
</head>
<body>
    {% include 'layout/top_nav.html' %}
    {% include 'layout/nav.html' %}
    
    {% block content %}
        
    {% endblock content %}
    
    {% include 'layout/footer.html' %}
    {% include 'layout/bottom_footer.html' %}

    <script src="https://code.jquery.com/jquery.min.js"></script>
    
    <!-- Bootstrap JS form CDN -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    
    <!-- jQuery sticky menu -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    
    <!-- jQuery easing -->
    <script src="{% static 'js/jquery.easing.1.3.min.js' %}"></script>
    
    <!-- Main Script -->
    <script src="{% static 'js/main.js' %}"></script>
    
    <!-- Slider -->
    <script type="text/javascript" src="{% static 'js/bxslider.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/script.slider.js' %}"></script>

    <!-- CONTACTFORMS SCRIPT -->
    <script src="{% static 'forms/js/jquery.min.js' %}"></script>
    <script src="{% static 'forms/js/popper.js' %}"></script>
    <script src="{% static 'forms/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'forms/js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'forms/js/main.js' %}"></script>
</body>
</html>

templates/layout/bottom_footer.html
{% load static %}

<div class="footer-bottom-area">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="copyright">
                    <p>&copy; 2015 uCommerce. All Rights Reserved. <a href="http://www.freshdesignweb.com" target="_blank">freshDesignweb.com</a></p>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="footer-card-icon">
                    <i class="fa fa-cc-discover"></i>
                    <i class="fa fa-cc-mastercard"></i>
                    <i class="fa fa-cc-paypal"></i>
                    <i class="fa fa-cc-visa"></i>
                </div>
            </div>
        </div>
    </div>
</div> 

templates/layout/footer.html
{% load static %}
{% load custom_tags %}
<div class="footer-top-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
           <div class="col-lg-3 col-md-6">

            {% footer_contact %}
            
                <div class="footer-social">
                    {% footer_social %}
                </div>  
            </div>
            
      
            {% footer_part_menu 'User Navigation' 'My account' 'Order History' 'Wishlist' 'Vendor contact' 'Front page' %}
          
            {% footer_part_menu 'Categories' 'Mobile phone' 'Home accesseries' 'LED TV' 'Computer' 'Gadets' %}
           
        </div>
    </div>
</div>

templates/layout/nav.html
{% load static %}
{% load custom_tags %}
<div class="site-branding-area">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="logo">
                    <h1><a href="./"><img src="{% static 'img/logo.png' %}"></a></h1>
                </div>
            </div>

            <div class="col-sm-6">
                <div class="shopping-item">
                    <a href="{% url 'cart:cart_detail' %}">Cart - <span class="cart-amunt">$0</span> <i class="fa fa-shopping-cart"></i>
                        <span class="product-count">5</span></a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="mainmenu-area">
    <div class="container">
        <div class="row">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    {% for item in menu %}
                        <li><a href="{% url item.url %}">{{ item.title }}</a></li>
                    {% endfor %}
                        
                    {% comment %}
                        
                    
                    <li><a href="{% url 'mainpage:show_mainpage' %}">Home</a></li>
                    <li><a href="{% url 'pages:all_products' %}">Shop page</a></li>
                    <li><a href="{% url 'cart:cart_detail' %}">Cart</a></li>
                    <li><a href="{% url 'contacts:contact_page_form_view' %}">Contacts</a></li> 
                    
                    {% nav_menu %}
                    {% endcomment %}
                </ul>
            </div>
        </div>
    </div>
</div>

templates/layout/top_nav.html
{% load static %}

<div class="header-area">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="user-menu">
                    <ul>
                        {% if user.is_authenticated %}
                        <li><a href="#"><i class="fa fa-user"></i>{{ user.username }}</a></li>
                        {% endif %}
                        <li><a href="#"><i class="fa fa-heart"></i> Wishlist</a></li>
                        <li><a href="cart.html"><i class="fa fa-user"></i> My Cart</a></li>
                        <li><a href="checkout.html"><i class="fa fa-user"></i> Checkout</a></li>
                        
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'logout' %}"><i class="fa fa-user"></i>Logut</a></li>
                        {% else %}
                        <li><a href="{% url 'login' %}"><i class="fa fa-user"></i>Login</a></li>
                        {% endif %}
                            
                        
                    </ul>
                </div>
            </div> 
        </div>
    </div>
</div>